### ISSUE TITLE
Check-up gesprek Maandag 15-06-2020

### ISSUE THREAD

**Issue by JRMfer** [SyrkavanKuppenveld/progressierups#2]
- Code en structuur van de Github repository ziet et er keurig en strak uit :-)
- Er zijn veel "dezelfde soort bestanden". Als jullie daar klaar mee zijn dan raad ik het aan om de bestanden van de repository af te halen.
- Sommige algoritmes houden nog geen rekening met collisions. Misschien een idee om deze 1-voor-1 "te verbeteren"?
- Er is nu een deterministische versie van een greedy geïmplementeerd. Dit geeft echter altijd hetzelfde antwoord. Misschien een idee om ergens in de algoritme een random element toe te voegen?

**Comment by SyrkavanKuppenveld** [comment]
Punt 0: top!
Punt 1: verwerkt
Punt 2: staat op de planning
Punt 3: we hebben twee varianten op de greedy met elk een ander random element ( (1) random kiezen met welke net wordt begonnen en (2) random keuzes in pad bij gelijkwaardige kosten pad)

**Comment by SyrkavanKuppenveld** [comment]
Alle punten zijn nu verwerkt!
