### ISSUE TITLE
Check-up gesprek Vrijdag 19-06-2020

### ISSUE THREAD

**Issue by JRMfer** [SyrkavanKuppenveld/progressierups#3]
- Uitleg mappenstructuur heeft een kleine "fout" (code/classes i.p.v. code/algorithms)
- Maak een map __results__ aan voor je resultaten.
- Zet wat "header-info" bovenaan je bestanden.
- Let op de volgorde van je "imports" en importeer niet heel veel functies op 1 regel. Het is dan beter om de algehele package te importeren (import code.algorithms as algo)
- Laat geen onnodige code, commentaar en/of print statements achter!
- Er is nog een .DS_store bestand.
- Kijk uit met variabelenamen zoals __copy__. Dit zijn gereserveerde namen en hebben binnen Python al een specifieke functionaliteit.
- De functie __create_path__ is vrij lang. Verdeel de functionaliteit anders in meerder functies (e.g., het bewegen over de assen).
- Er zijn veel "gelijksoortige" bestanden. Misschien dat inheritance uitweg kan bieden?
- Commentaar en docstrings zien er echt heel keurig uit :-)

**Comment by SyrkavanKuppenveld** [comment]
Alle bovenstaande punten zijn verwerkt behoudens de volgende:
Punt 3: dit lukt nog niet, gaan we morgen (maandag 22-06) verder naar kijken
Punt 4: zo goed als overal weggehaald behalve bij de functies die no under construction zijn

**Comment by SyrkavanKuppenveld** [comment]
Da laatste puntjes zijn gisteren verwerkt!
